### ISSUE TITLE
PA-review: auth

### ISSUE THREAD

**Issue by odangitsdjang** [odangitsdjang/Flix#2]

**Comment by odangitsdjang** [comment]
Finished, with heroku! 
I'm going to link the heroku right now

**Comment by odangitsdjang** [comment]
https://flix1.herokuapp.com/#/

**Comment by anastassia-b** [comment]
Log-in and Sign-up work perfectly with the right credentials. However, no errors are being rendered when a field is missing on submission or when one submits with the wrong credentials.

**Comment by anastassia-b** [comment]
Great, works well.
